### PR TITLE
Tiny fix of `Coevolve()` with the dependency graph check

### PR DESCRIPTION
**Pull request by palmtree2013**
this pull request is related to https://github.com/SciML/JumpProcesses.jl/pull/276#issuecomment-1372219257

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Can you add a test which catches this? I guess it should be a case with mixed jumps?

**Comment by ChrisRackauckas** [comment]
Use Catalyst to generate the problem so it has the dependency graph? Or use one of the hand-built ones and extend it?

**Comment by isaacsas** [comment]
I just added a test for this based on the MWE.

**Review by isaacsas — APPROVED** [review]
GTG if tests pass I think.

**Comment by isaacsas** [comment]
Thanks @palmtree2013

**Comment by palmtree2013** [comment]
Thank you for adding the test

**Pull request merged**
