### PR TITLE
Juliacon2023 Revision

### PR DESCRIPTION
**Pull request by gzagatti**
This PR contains the revision on the latest draft of the paper. Changes that I have made throughout the paper are commented.

Please also find the [PDF version](https://github.com/SciML/JumpProcesses.jl/files/11398126/paper.pdf) for easy reference.

### CODE REVIEW

**Comment by isaacsas** [comment]
CI doesn't seem to have run on your most recent commits? 

Happy to merge when you say it is done, and CI has run through ok.

**Comment by gzagatti** [comment]
@isaacsas I pushed the final version of the draft with the benchmark figures. 

Unfortunately, the format check keeps failing. I did run JuliaFormatter multiple times, but no more formatting is performed. So I don't know why CI keeps failing on that. Can you help?

**Comment by isaacsas** [comment]
Formatting is failing on files in the paper subfolder. I'd suggest either excluding that folder, or running the formatter on them.

Also, why has CI stopped running with your recent commits? It was running before, but now seems to have stopped.

**Comment by gzagatti** [comment]
@isaacsas, all CI tests passed. The Invalidations job was skipped as it is only executed in the main branch.

**Comment by isaacsas** [comment]
CI didn’t that calls the test/*.jl still didn’t run.

**Comment by gzagatti** [comment]
Which test is this one? I can't find it.

**Comment by gzagatti** [comment]
Is it this workflow: https://github.com/SciML/JumpProcesses.jl/blob/master/.github/workflows/CI.yml

I think it's only supposed to run on the master branch:

```yml
name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
```

**Comment by isaacsas** [comment]
Huh, that’s weird. Wonder why it was running before. The PR was still set to merge to a branch at that point I thought. 

Have you run tests locally to make sure there are no issues? It would suck to submit it and then have someone have code problems on this branch.

**Comment by isaacsas** [comment]
Or is this fully up to date with master now?

**Comment by gzagatti** [comment]
Yes, I merged with master. Doing a diff returns no difference from master:

```sh
git diff origin/master --name-only | grep -v '^paper'
```

**Comment by isaacsas** [comment]
Great, all merged. Thanks!

**Pull request merged**
