### PR TITLE
Move spatial tutorial from SciMLTutorials

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Now that we have package docs for all of the packages and doctests, it makes sense for the tutorials to be built as part of the testing process. It also keeps everything organized by package. Thus SciMLTutorials is getting cannibalized into separate package docs, and this is the one for JumpProcesses. I did a few updates (DiffEqJump, LightGraphs, links) so hopefully this is enough. I might need a little bit of help getting this one completed though, since there are a few I need to tend to.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@Vilin97 @isaacsas

**Comment by isaacsas** [comment]
I can finish this one off.

**Comment by ChrisRackauckas** [comment]
Thanks, I'll just close the tab then and move onto the next!

**Comment by ChrisRackauckas** [comment]
Looks like this just worked. Okay!

**Comment by isaacsas** [comment]
The tutorial needs some updates, but I can followup with those.

**Pull request merged**
